export const CONFIG = {
  APP_MAX_DETALLE_CHARACTERS: process.env.NEXT_PUBLIC_APP_MAX_DETALLE_CHARACTERS
    ? parseInt(process.env.NEXT_PUBLIC_APP_MAX_DETALLE_CHARACTERS)
    : 5000,
  USIG_API_URL: process.env.NEXT_PUBLIC_USIG_API_URL,
  GOOGLE_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY,
  GOOGLE_MAP_ID: process.env.NEXT_PUBLIC_GOOGLE_MAP_ID,
  GOOGLE_MAP_SECRET_KEY: process.env.GOOGLE_MAP_SECRET_KEY || '',
  GOOGLE_RECAPTCHA_SECRET_KEY: process.env.GOOGLE_RECAPTCHA_SECRET_KEY,
  MPF_DENUNCIA_ORIGEN: process.env.NEXT_PUBLIC_MPF_DENUNCIA_ORIGEN || 'DENMOB',
  MPF_DENUNCIA_ORIGEN_ORGANISMO:
    process.env.NEXT_PUBLIC_MPF_DENUNCIA_ORIGEN_ORGANISMO || 'WEB',
  MPFAPI_URL: process.env.MPFAPI_URL,
  SITIOAPI_BARRIOS_ENDPOINT:
    process.env.NEXT_PUBLIC_SITIOAPI_BARRIOS_ENDPOINT || '',
  KIWIAPI_URL: process.env.KIWIAPI_URL,
  SMTP_FROM: process.env.SMTP_FROM,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_TLS: process.env.SMTP_TLS === 'true' || false,
  SMTP_USERNAME: process.env.SMTP_USERNAME,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  SMTP_PORT: Number(process.env.SMTP_PORT) || 587,
  LEYIA_ENABLED: process.env.LEYIA_ENABLED || false,
  LANGFLOW_EMBEDDED_CHAT_BUNDLE:
    process.env.LANGFLOW_EMBEDDED_CHAT_BUNDLE ||
    'https://cdn.jsdelivr.net/gh/logspace-ai/langflow-embedded-chat@v1.0.7/dist/build/static/js/bundle.min.js',
  LANGFLOW_EMBEDDED_CHAT_URL: process.env.LANGFLOW_EMBEDDED_CHAT_URL || '',
  LANGFLOW_EMBEDDED_CHAT_FLOW_ID:
    process.env.LANGFLOW_EMBEDDED_CHAT_FLOW_ID || '',
  LANGFLOW_EMBEDDED_CHAT_API_KEY:
    process.env.LANGFLOW_EMBEDDED_CHAT_API_KEY || '',
  LANGFLOW_EMBEDDED_CHAT_TITLE:
    process.env.LANGFLOW_EMBEDDED_CHAT_TITLE || 'leyIA',
  LANGFLOW_EMBEDDED_CHAT_TRIGGER_WIDTH:
    process.env.NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_WIDTH || 80,
  LANGFLOW_EMBEDDED_CHAT_TRIGGER_HEIGHT:
    process.env.NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_HEIGHT || 80,
  IFCONFIGME_URL:
    process.env.NEXT_PUBLIC_IFCONFIGME_URL || 'https://ifconfig.me/ip',
  MATOMO_URL: process.env.NEXT_PUBLIC_MATOMO_URL || '',
  MATOMO_SITE_ID: process.env.NEXT_PUBLIC_MATOMO_SITE_ID || '',
  N8N_WEBHOOK_LEYIA_CHAT: process.env.NEXT_PUBLIC_N8N_WEBHOOK_LEYIA_CHAT || '',
  NUBAX_POC_LEYIA_URL: process.env.NEXT_PUBLIC_NUBAX_POC_LEYIA_URL || ''
};
