FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
ARG NEXT_PUBLIC_USIG_API_URL
ENV NEXT_PUBLIC_USIG_API_URL=$NEXT_PUBLIC_USIG_API_URL
ARG NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_GOOGLE_MAP_ID
ENV NEXT_PUBLIC_GOOGLE_MAP_ID=$NEXT_PUBLIC_GOOGLE_MAP_ID
ARG GOOGLE_RECAPTCHA_SECRET_KEY
ENV GOOGLE_RECAPTCHA_SECRET_KEY=$GOOGLE_RECAPTCHA_SECRET_KEY
ARG GOOGLE_MAP_SECRET_KEY
ENV GOOGLE_MAP_SECRET_KEY=$GOOGLE_MAP_SECRET_KEY
ARG MPFAPI_URL
ENV MPFAPI_URL=$MPFAPI_URL
ARG KIWIPI_URL
ENV KIWIPI_URL=$KIWIPI_URL
ARG SMTP_FROM
ENV SMTP_FROM=$SMTP_FROM
ARG SMTP_HOST
ENV SMTP_HOST=$SMTP_HOST
ARG SMTP_TLS
ENV SMTP_TLS=$SMTP_TLS
ARG SMTP_USERNAME
ENV SMTP_USERNAME=$SMTP_USERNAME
ARG SMTP_PASSWORD
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ARG LANGFLOW_EMBEDDED_CHAT_BUNDLE
ENV LANGFLOW_EMBEDDED_CHAT_BUNDLE=$LANGFLOW_EMBEDDED_CHAT_BUNDLE
ARG LANGFLOW_EMBEDDED_CHAT_URL
ENV LANGFLOW_EMBEDDED_CHAT_URL=$LANGFLOW_EMBEDDED_CHAT_URL
ARG LANGFLOW_EMBEDDED_CHAT_FLOW_ID
ENV LANGFLOW_EMBEDDED_CHAT_FLOW_ID=$LANGFLOW_EMBEDDED_CHAT_FLOW_ID
ARG LANGFLOW_EMBEDDED_CHAT_TITLE
ENV LANGFLOW_EMBEDDED_CHAT_TITLE=$LANGFLOW_EMBEDDED_CHAT_TITLE
ARG LANGFLOW_EMBEDDED_CHAT_API_KEY
ENV LANGFLOW_EMBEDDED_CHAT_API_KEY=$LANGFLOW_EMBEDDED_CHAT_API_KEY
ARG NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_WIDTH
ENV NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_WIDTH=$NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_WIDTH
ARG NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_HEIGHT
ENV NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_HEIGHT=$NEXT_PUBLIC_LANGFLOW_EMBEDDED_CHAT_TRIGGER_HEIGHT
ARG NEXT_PUBLIC_MATOMO_URL
ENV NEXT_PUBLIC_MATOMO_URL=$NEXT_PUBLIC_MATOMO_URL
ARG NEXT_PUBLIC_MATOMO_SITE_ID
ENV NEXT_PUBLIC_MATOMO_SITE_ID=$NEXT_PUBLIC_MATOMO_SITE_ID
ARG NEXT_PUBLIC_SITIOAPI_BARRIOS_ENDPOINT
ENV NEXT_PUBLIC_SITIOAPI_BARRIOS_ENDPOINT=$NEXT_PUBLIC_SITIOAPI_BARRIOS_ENDPOINT
ARG NEXT_PUBLIC_N8N_WEBHOOK_LEYIA_CHAT
ENV NEXT_PUBLIC_N8N_WEBHOOK_LEYIA_CHAT=$NEXT_PUBLIC_N8N_WEBHOOK_LEYIA_CHAT
ARG NEXT_PUBLIC_NUBAX_POC_LEYIA_URL
ENV NEXT_PUBLIC_NUBAX_POC_LEYIA_URL=$NEXT_PUBLIC_NUBAX_POC_LEYIA_URL

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000
CMD HOSTNAME="0.0.0.0" node server.js
